general {
    lock_cmd = ~/.local/bin/hyprlock-random.sh
    before_sleep_cmd = ~/.local/bin/hyprlock-random.sh
    after_sleep_cmd = bash -c '[ -f "$HOME/.config/hypr/hyprland.lua" ] && hyprctl eval "hl.dispatch(hl.dsp.dpms({action=\"on\"}))" || hyprctl dispatch dpms on'
}

listener {
    timeout = 1800 # 30 minutes
    on-timeout = ~/.local/bin/hyprlock-random.sh
}
