general {
    disable_loading_bar = false
    hide_cursor = true
    grace = 5
    no_fade_in = false
}

background {
    monitor =
    color = rgba(34, 36, 54, 1.0)
    blur_passes = 3
    blur_size = 7
    noise = 0.0117
    contrast = 1.3
    brightness = 0.8
    vibrancy = 0.21
    vibrancy_darkness = 0.0
}

input-field {
    monitor =
    size = 300, 50
    outline_thickness = 2
    dots_size = 0.26
    dots_spacing = 0.64
    dots_center = true
    dots_rounding = -1
    outer_color = rgb(134, 225, 252)
    inner_color = rgb(47, 51, 77)
    font_color = rgb(200, 211, 245)
    fade_on_empty = true
    fade_timeout = 1000
    placeholder_text = <i>Password...</i>
    hide_input = false
    rounding = 8
    check_color = rgb(79, 214, 190)
    fail_color = rgb(255, 117, 127)
    fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>
    capslock_color = rgb(255, 199, 119)
    position = 0, -100
    halign = center
    valign = center
}

label {
    monitor =
    text = $TIME
    color = rgba(200, 211, 245, 1.0)
    font_size = 64
    font_family = JetBrainsMono Nerd Font
    position = 0, 100
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:60000] date +"%A, %d %B %Y"
    color = rgba(130, 139, 184, 1.0)
    font_size = 18
    font_family = JetBrainsMono Nerd Font
    position = 0, 20
    halign = center
    valign = center
}
