wallpaper {
    monitor = DP-1
    path = /home/tiago/Pictures/Wallpapers
    fit_mode = cover
    timeout = 86400 # 24 hours
}

wallpaper {
    monitor = eDP-1
    path = /home/tiago/Pictures/Wallpapers
    fit_mode = cover
    timeout = 86400 # 24 hours
}

splash = false
ipc = on
