[env]
TERM = "xterm-256color"

[window]
dimensions.columns = 216
dimensions.lines = 59
position.x = 0
position.y = 0
opacity = 0.97
startup_mode = "Windowed"
decorations = "none"
decorations_theme_variant = "None"
padding = { x = 16, y = 14 }

[scrolling]
history = 100000

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
size = 12

# [keyboard]
# bindings = [
#   { key = "Left", mods = "Alt", chars = "^[[1;3D" },
#   { key = "Right", mods = "Alt", chars = "^[[1;3C" },
# ]

# TokyoNight Alacritty Colors
# Default colors
[colors.primary]
background = '#222436'
foreground = '#c8d3f5'

#[colors.cursor]
#cursor = '#c8d3f5'
#text = '#222436'

# Normal colors
[colors.normal]
black = '#1b1d2b'
red = '#ff757f'
green = '#c3e88d'
yellow = '#ffc777'
blue = '#82aaff'
magenta = '#c099ff'
cyan = '#86e1fc'
white = '#828bb8'

# Bright colors
[colors.bright]
black = '#444a73'
red = '#ff757f'
green = '#c3e88d'
yellow = '#ffc777'
blue = '#82aaff'
magenta = '#c099ff'
cyan = '#86e1fc'
white = '#c8d3f5'

# Indexed Colors
[[colors.indexed_colors]]
index = 16
color = '#ff966c'

[[colors.indexed_colors]]
index = 17
color = '#c53b53'
